development:
  secret_key_base: e42629d323a94a68dfd5e2c2abf75b33dd5aaa33a2d8636499f86b2bbfb317d7217767c50d0a2438c9a9a2f49a31c5f8e5e0d054891f90c7e888d996fcc2db4b
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: bc4dcfb4b4078587583774896ac7b551b11463f2ab5b418c8fad4703df7654d4d06b9093df747597896e2e7556d6feb098f1f537cd74ce241327a8ecf903fc80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
